{
 "title": "RedLab & MSCL Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RedLab-TC Historical Data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"daq_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MicroStrain Sensor Data (Radio Stream)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "newton" } },
   "targets": [
    {
     "query": "from(bucket: \"daq_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mscl_sensors\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"source\"] == \"mscl_config_stream\")\n  |> filter(fn: (r) => r[\"channel\"] == \"ch1\")\n  |> map(fn: (r) => ({ r with _value: 1000000.0 / (0.32333116 * r._value) }))\n  |> yield(name: \"radio\")"
    }
   ]
  },
  {
   "title": "MicroStrain Sensor Data (Node Export Stream)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "newton" } },
   "targets": [
    {
     "query": "from(bucket: \"daq_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mscl_sensors\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"source\"] == \"mscl_node_export\")\n  |> filter(fn: (r) => r[\"channel\"] == \"ch1\")\n  |> map(fn: (r) => ({ r with _value: 1000000.0 / (0.32333116 * r._value) }))\n  |> yield(name: \"node_export\")"
    }
   ]
  }
 ]
}